Ext.define('Onlineshopping.onlineshopping.web.shop.view.retail.ItemTemplate', {
     "xtype": "itemTemplate",
     "items": [{
          "xtype": "hiddenfield",
          "fieldLabel": "itemId",
          "bindable": "itemId",
          "margin": 5,
          "name": "itemId",
          "title": "itemId",
          "itemId": "hmolbhi",
          "bind": "{itemId}"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Product",
          "margin": 5,
          "bindable": "productName",
          "name": "productName",
          "title": "Product",
          "itemId": "ikmkdki",
          "bind": "{productName}"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Brand",
          "margin": 5,
          "bindable": "brandName",
          "name": "brandName",
          "title": "Brand",
          "itemId": "lfjoehi",
          "bind": "{brandName}"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Category",
          "margin": 5,
          "bindable": "categoryName",
          "name": "categoryName",
          "title": "Category",
          "itemId": "iandiki",
          "bind": "{categoryName}"
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Name",
          "margin": 5,
          "bindable": "itemName",
          "name": "itemName",
          "title": "Name",
          "itemId": "ngeopji",
          "bind": "{itemName}"
     }, {
          "xtype": "image",
          "name": "itemIcon",
          "height": 100,
          "width": 100,
          "border": true,
          "margin": 5,
          "bindable": "itemIcon",
          "itemId": "cnolcli",
          "bind": {
               "src": "{itemIcon}"
          }
     }, {
          "xtype": "displayfield",
          "fieldLabel": "Price",
          "margin": 5,
          "bindable": "itemPrice",
          "name": "itemPrice",
          "title": "Price",
          "itemId": "pbpfopi",
          "bind": "{itemPrice}"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "Quantity",
          "name": "cartQty",
          "margin": 5,
          "bindable": "cartQty",
          "title": "Quantity",
          "itemId": "flaldei",
          "bind": "{cartQty}"
     }, {
          "xtype": "button",
          "name": "addtocart",
          "text": "Add To Cart",
          "margin": 5,
          "isSubmitBtn": true,
          "itemId": "bdmgjli",
          "listeners": {
               "click": "onaddtocartclick"
          }
     }],
     "margin": 5,
     "border": true,
     "autoScroll": true,
     "title": "Panel",
     "isPartialUI": true,
     "itemId": "lmpphbi",
     "dockedItems": [],
     "extend": "Ext.panel.Panel",
     "requires": ["Onlineshopping.onlineshopping.web.shop.controller.retail.ItemTemplateController", "Onlineshopping.onlineshopping.shared.shop.viewmodel.retail.ItemTemplateViewModel", "Onlineshopping.onlineshopping.shared.shop.model.retail.ItemTemplateModel"],
     "viewModel": "ItemTemplateViewModel",
     "controller": "ItemTemplateController"
});