Ext.define('Onlineshopping.onlineshopping.web.shop.view.retail.PartialItem', {
     "xtype": "partialItem",
     "items": [{
          "xtype": "hiddenfield",
          "fieldLabel": "itemId",
          "bindable": "itemId",
          "margin": 5,
          "name": "itemId",
          "itemId": "dnapkji",
          "bind": "{itemId}"
     }, {
          "xtype": "textfield",
          "fieldLabel": "Product",
          "margin": 5,
          "bindable": "productName",
          "name": "productName",
          "itemId": "pcfelmi",
          "bind": "{productName}"
     }, {
          "xtype": "textfield",
          "fieldLabel": "Brand",
          "margin": 5,
          "bindable": "brandName",
          "name": "brandName",
          "itemId": "cdmgjfi",
          "bind": "{brandName}"
     }, {
          "xtype": "textfield",
          "fieldLabel": "Category",
          "margin": 5,
          "bindable": "categoryName",
          "name": "categoryName",
          "itemId": "hhdhofi",
          "bind": "{categoryName}"
     }, {
          "xtype": "textfield",
          "fieldLabel": "Item",
          "margin": 5,
          "bindable": "itemName",
          "name": "itemName",
          "itemId": "mbhcfki",
          "bind": "{itemName}"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "Price",
          "name": "itemPrice",
          "margin": 5,
          "bindable": "itemPrice",
          "itemId": "keedfli",
          "bind": "{itemPrice}"
     }, {
          "xtype": "numberfield",
          "fieldLabel": "Quantity",
          "name": "cartQty",
          "margin": 5,
          "bindable": "cartQty",
          "itemId": "hgeaeji",
          "bind": "{cartQty}"
     }, {
          "xtype": "button",
          "text": "addToCart",
          "isSubmitBtn": true,
          "margin": 5,
          "name": "addToCart",
          "itemId": "mnmjdci",
          "listeners": {
               "click": "onaddToCartclick"
          }
     }],
     "margin": 5,
     "border": true,
     "autoScroll": true,
     "title": "Panel",
     "itemId": "gipllpi",
     "dockedItems": [],
     "extend": "Ext.panel.Panel",
     "requires": ["Onlineshopping.onlineshopping.web.shop.controller.retail.PartialItemController", "Onlineshopping.onlineshopping.shared.shop.viewmodel.retail.PartialItemViewModel", "Onlineshopping.onlineshopping.shared.shop.model.retail.PartialItemModel"],
     "viewModel": "PartialItemViewModel",
     "controller": "PartialItemController"
});