Ext.define('Onlineshopping.onlineshopping.shared.shop.model.retail.ItemModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "product",
          "reference": "Product",
          "defaultValue": ""
     }, {
          "name": "brand",
          "reference": "Brand",
          "defaultValue": ""
     }, {
          "name": "category",
          "reference": "Category",
          "defaultValue": ""
     }, {
          "name": "itemName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "itemPrice",
          "type": "number",
          "defaultValue": ""
     }, {
          "name": "itemStock",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "itemIcon",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});